# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_auto_20151213_0804'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='Choise',
        ),
    ]
